name: R6 Drops Telegram Notify (daily)

on:
  schedule:
    # Runs every day at 07:00 UTC (≈08:00 CET / 09:00 CEST)
    - cron: "0 7 * * *"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure jq is available
        run: jq --version

      - name: Read latest JSON
        run: |
          if [ ! -f latest_r6.json ]; then
            echo '{}' > latest_r6.json
          fi
          jq -r '.count // 0' latest_r6.json > count.txt
          jq -r '.cards[].title // empty' latest_r6.json | sort -u > titles.txt

      - name: Build message
        id: msg
        run: |
          COUNT=$(cat count.txt)
          if [ "$COUNT" -eq 0 ]; then
            echo "TEXT=No Rainbow Six drops today." >> $GITHUB_OUTPUT
          else
            LIST=$(head -n 10 titles.txt | sed 's/^/• /')
            EXTRA=$(wc -l < titles.txt)
            if [ "$EXTRA" -gt 10 ]; then
              EXTRA_MSG="… and $((EXTRA-10)) more"
            else
              EXTRA_MSG=""
            fi
            printf "TEXT=R6 Drops: %s campaigns%%0A%%0A%s%%0A%s\n" "$COUNT" "$LIST" "$EXTRA_MSG" >> $GITHUB_OUTPUT
          fi

      - name: Send Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="${{ steps.msg.outputs.TEXT }}" \
            -d disable_web_page_preview=true
