name: R6 Drops Telegram Notify

on:
  schedule:
    - cron: "0 7,12 * * *"   # adjust as you like (UTC)
  workflow_dispatch: {}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure JSON exists
        run: |
          if [ ! -f latest_r6.json ]; then
            echo '{}' > latest_r6.json
          fi

           - name: Build message (with timeframes)
        id: msg
        run: |
          COUNT=$(jq -r '.count // 0' latest_r6.json)
          SCRAPED=$(jq -r '.scraped_at // empty' latest_r6.json)

          # Format "as of" as MM-DD (UTC). Fallback to today if missing.
          if [ -n "$SCRAPED" ]; then
            ASOF=$(date -u -d "$SCRAPED" +"%m-%d" 2>/dev/null || echo "${SCRAPED:5:5}")
          else
            ASOF=$(date -u +"%m-%d")
          fi

          # Build "Title — Timeframe" lines, unique and trimmed
          jq -r '.cards[] | "\(.title // "Untitled") — \(.timeframe // "Time N/A")"' latest_r6.json \
          | sed 's/[[:space:]]\{1,\}/ /g' \
          | sed 's/ —  — / — Time N\/A/' \
          | sort -u > lines.txt

          # Prepare up to 8 entries
          PREVIEW=$(head -n 8 lines.txt | sed 's/^/• /')
          TOTAL=$(wc -l < lines.txt)
          if [ "$TOTAL" -gt 8 ]; then
            EXTRA_MSG="… and $((TOTAL-8)) more"
          else
            EXTRA_MSG=""
          fi

          if [ "$COUNT" -eq 0 ]; then
            printf "TEXT=No Rainbow Six drops today%%0Aas of %s (UTC)\n" "$ASOF" >> $GITHUB_OUTPUT
          else
            PREVIEW_ENC=$(printf "%s" "$PREVIEW" | sed ':a;N;$!ba;s/\n/%0A/g')
            printf "TEXT=R6 Drops: %s campaigns%%0Aas of %s (UTC)%%0A%%0A%s%%0A%s\n" "$COUNT" "$ASOF" "$PREVIEW_ENC" "$EXTRA_MSG" >> $GITHUB_OUTPUT
          fi


      - name: Send Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="${{ steps.msg.outputs.TEXT }}" \
            -d disable_web_page_preview=true
