name: R6 Drops Telegram Notify

on:
  schedule:
    # 07:00 UTC (≈ 08:00 CET right now). Add a second run at 12:00 UTC for testing today.
    - cron: "0 7,12 * * *"
  workflow_dispatch: {}   # lets you trigger it manually

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure JSON exists
        run: |
          if [ ! -f latest_r6.json ]; then
            echo '{}' > latest_r6.json
          fi

      - name: Build message
        id: msg
        run: |
          COUNT=$(jq -r '.count // 0' latest_r6.json)
          TITLES=$(jq -r '.cards[].title // empty' latest_r6.json | sort -u)
          if [ "$COUNT" -eq 0 ]; then
            echo "TEXT=No Rainbow Six drops today." >> $GITHUB_OUTPUT
          else
            LIST=$(echo "$TITLES" | head -n 10 | sed 's/^/• /')
            EXTRA=$(echo "$TITLES" | wc -l)
            if [ "$EXTRA" -gt 10 ]; then
              EXTRA_MSG="… and $((EXTRA-10)) more"
            else
              EXTRA_MSG=""
            fi
            printf "TEXT=R6 Drops: %s campaigns%%0A%%0A%s%%0A%s\n" "$COUNT" "$LIST" "$EXTRA_MSG" >> $GITHUB_OUTPUT
          fi

      - name: Send Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="${{ steps.msg.outputs.TEXT }}" \
            -d disable_web_page_preview=true
